apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../components/gitops-operator/production
- ../../../../components/argocd-instance/production
- ../../../../components/argocd/projects
- ../../../../components/argocd/apps