apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../components/gitops-operator/sandbox
- ../../../../components/argocd-instance/sandbox
- ../../../../components/argocd/projects
- ../../../../components/argocd/apps
