apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc
  project: sampleapp
  source:
    path: pricelist/
    repoURL: https://github.com/christianh814/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
     - group: route.openshift.io
       name: pricelist-route
       kind: Route
       jsonPointers:
         - /spec/host
